CREATE TABLE AttributeVod (
  VOD_TYPE VARCHAR2(4000),
  VOD_NAME VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  LOCKED_FLAG VARCHAR2(4000),
  OBJECT_NUMBER VARCHAR2(4000),
  CONSTRAINT PK_AttributeVod PRIMARY KEY (ROW_ID)
);
CREATE TABLE ClassVod (
  VOD_TYPE VARCHAR2(4000),
  VOD_NAME VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  LOCKED_FLAG VARCHAR2(4000),
  OBJECT_NUMBER VARCHAR2(4000),
  CONSTRAINT PK_ClassVod PRIMARY KEY (ROW_ID)
);
CREATE TABLE ProductVod (
  VOD_TYPE VARCHAR2(4000),
  VOD_NAME VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  LOCKED_FLAG VARCHAR2(4000),
  OBJECT_NUMBER VARCHAR2(4000),
  CONSTRAINT PK_ProductVod PRIMARY KEY (ROW_ID)
);
CREATE TABLE VodTranslation (
  VOD_NAME VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  CONSTRAINT PK_VodTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE VodVersion (
  VERSION_NUMBER VARCHAR2(4000),
  VERSION_ID VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  START_DATE VARCHAR2(4000),
  CURRENT_VERSION_FLAG VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  END_DATE VARCHAR2(4000),
  RELEASED_FLAG VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  ACTIVE_FLAG VARCHAR2(4000),
  CONSTRAINT PK_VodVersion PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_VodVersion_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE AttributeDefinition (
  FIRST_VERSION VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  MINIMUM_VALUE VARCHAR2(4000),
  INCREMENT_VALUE VARCHAR2(4000),
  UNIT_OF_MEASURE_CODE VARCHAR2(4000),
  DATA_TYPE_CODE VARCHAR2(4000),
  DOMAIN_TYPE_CODE VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  MAXIMUM_VALUE VARCHAR2(4000),
  CONSTRAINT PK_AttributeDefinition PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_AttributeDefinition_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE AttributeValue (
  ORIGINAL_ID VARCHAR2(4000),
  ACTIVE_FLAG VARCHAR2(4000),
  LANGUAGE_INDEPENDENT_CODE_VALUE VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  CONSTRAINT PK_AttributeValue PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_AttributeValue_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE AttributeValueTranslation (
  ROW_ID VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  LANGUAGE_INDEPENDENT_CODE_VALUE VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  CONSTRAINT PK_AttributeValueTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE ProductDefinition (
  ALIAS_NAME VARCHAR2(4000),
  BILLABLE_FLAG VARCHAR2(4000),
  ACTIVE_FLAG VARCHAR2(4000),
  NAME VARCHAR2(4000),
  FULFILLMENT_ITEM_CODE VARCHAR2(4000),
  CONFIGURATION_MODEL_ID VARCHAR2(4000),
  PRIMARY_PRODUCT_LINE VARCHAR2(4000),
  PRIMARY_POSITION VARCHAR2(4000),
  BUSINESS_UNIT_ID VARCHAR2(4000),
  EFFECTIVE_START_DATE VARCHAR2(4000),
  CURCY_CD VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  EFFECTIVE_END_DATE VARCHAR2(4000),
  PART_NUMBER VARCHAR2(4000),
  VERSION VARCHAR2(4000),
  STATUS VARCHAR2(4000),
  TYPE VARCHAR2(4000),
  INTEGRATION_PRODUCT_TYPE VARCHAR2(4000),
  PRODUCT_CODE VARCHAR2(4000),
  PRODUCT_TYPE_CODE VARCHAR2(4000),
  PROMOTION_INSTANCE_CODE VARCHAR2(4000),
  PROMOTION_TYPE_CODE VARCHAR2(4000),
  UNIT_OF_MEASURE_CODE VARCHAR2(4000),
  PRICE_TYPE_CD VARCHAR2(4000),
  CONSTRAINT PK_ProductDefinition PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionDefinition (
  ALIAS_NAME VARCHAR2(4000),
  BILLABLE_FLAG VARCHAR2(4000),
  ACTIVE_FLAG VARCHAR2(4000),
  NAME VARCHAR2(4000),
  FULFILLMENT_ITEM_CODE VARCHAR2(4000),
  CONFIGURATION_MODEL_ID VARCHAR2(4000),
  PRIMARY_PRODUCT_LINE VARCHAR2(4000),
  PRIMARY_POSITION VARCHAR2(4000),
  BUSINESS_UNIT_ID VARCHAR2(4000),
  EFFECTIVE_START_DATE VARCHAR2(4000),
  CURCY_CD VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  EFFECTIVE_END_DATE VARCHAR2(4000),
  PART_NUMBER VARCHAR2(4000),
  VERSION VARCHAR2(4000),
  STATUS VARCHAR2(4000),
  TYPE VARCHAR2(4000),
  INTEGRATION_PRODUCT_TYPE VARCHAR2(4000),
  PRODUCT_CODE VARCHAR2(4000),
  PRODUCT_TYPE_CODE VARCHAR2(4000),
  PROMOTION_INSTANCE_CODE VARCHAR2(4000),
  PROMOTION_TYPE_CODE VARCHAR2(4000),
  UNIT_OF_MEASURE_CODE VARCHAR2(4000),
  PRICE_TYPE_CD VARCHAR2(4000),
  CONSTRAINT PK_PromotionDefinition PRIMARY KEY (ROW_ID)
);
CREATE TABLE ObjectDefinition (
  PARENT_VOD_VERSION VARCHAR2(4000),
  POST_PICK_CODE VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  PARENT_VOD_ID VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  PRE_PICK_CODE VARCHAR2(4000),
  SMART_PART_NUMBER_DEFINITION_ID VARCHAR2(4000),
  OBJECT_NAME VARCHAR2(4000),
  CONSTRAINT PK_ObjectDefinition PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_ObjectDefinition_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE ObjectDefinitionTranslation (
  ROW_ID VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  OBJECT_NAME VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  CONSTRAINT PK_ObjectDefinitionTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE ObjectRelationship (
  RELATIONSHIP_TYPE_CODE VARCHAR2(4000),
  DISPLAY_COMPONENT_FLAG VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DEFAULT_QUANTITY VARCHAR2(4000),
  SUB_OBJECT_CLASS_ID VARCHAR2(4000),
  SUB_OBJECT_PRODUCT_ID VARCHAR2(4000),
  PARENT_RELATIONSHIP_ID VARCHAR2(4000),
  RELATIONSHIP_NAME VARCHAR2(4000),
  DEFAULT_SUB_OBJECT_PRODUCT_ID VARCHAR2(4000),
  OPTION_FLAG VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  MINIMUM_QUANTITY VARCHAR2(4000),
  FORECAST_FLAG VARCHAR2(4000),
  SUB_OBJECT_PRODUCT_VERSION VARCHAR2(4000),
  DISPLAY_COMPONENT_PRICE_FLAG VARCHAR2(4000),
  MAXIMUM_QUANTITY VARCHAR2(4000),
  SUB_OBJECT_CLASS_VERSION VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  SUB_OBJECT_TYPE_CODE VARCHAR2(4000),
  CONSTRAINT PK_ObjectRelationship PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_ObjectRelationship_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE ObjectRelationshipDomain (
  RELATIONSHIP_TYPE_CODE VARCHAR2(4000),
  DISPLAY_COMPONENT_FLAG VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DEFAULT_QUANTITY VARCHAR2(4000),
  SUB_OBJECT_CLASS_ID VARCHAR2(4000),
  SUB_OBJECT_PRODUCT_ID VARCHAR2(4000),
  PARENT_RELATIONSHIP_ID VARCHAR2(4000),
  RELATIONSHIP_NAME VARCHAR2(4000),
  DEFAULT_SUB_OBJECT_PRODUCT_ID VARCHAR2(4000),
  OPTION_FLAG VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  MINIMUM_QUANTITY VARCHAR2(4000),
  FORECAST_FLAG VARCHAR2(4000),
  SUB_OBJECT_PRODUCT_VERSION VARCHAR2(4000),
  DISPLAY_COMPONENT_PRICE_FLAG VARCHAR2(4000),
  MAXIMUM_QUANTITY VARCHAR2(4000),
  SUB_OBJECT_CLASS_VERSION VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  SUB_OBJECT_TYPE_CODE VARCHAR2(4000),
  CONSTRAINT PK_ObjectRelationshipDomain PRIMARY KEY (ROW_ID)
);
CREATE TABLE ObjectRelationshipTranslation (
  LANGUAGE_ID VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  RELATIONSHIP_NAME VARCHAR2(4000),
  CONSTRAINT PK_ObjectRelationshipTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE ObjectUIProperty (
  PROPERTY_TYPE_CD VARCHAR2(4000),
  ITEM_VALUE_SPECIFICATION VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  ITEM_DEFINITION VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  PROPERTY_NAME VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  ITEM_TYPE_CODE VARCHAR2(4000),
  CONSTRAINT PK_ObjectUIProperty PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_ObjectUIProperty_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE ObjectUIPropertyTranslation (
  PARENT_ROW_ID VARCHAR2(4000),
  ITEM_VALUE_SPECIFICATION VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  CONSTRAINT PK_ObjectUIPropertyTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE LinkedItem (
  SYSTEM_KEYWORD_CODE VARCHAR2(4000),
  DEFAULT_VALUE VARCHAR2(4000),
  VARIABLE_NAME VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  EXEC_FLG VARCHAR2(4000),
  SORT_SPECIFICATION VARCHAR2(4000),
  SEARCH_SPECIFICATION VARCHAR2(4000),
  ACTIVE_FLG VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  FIELD_NAME VARCHAR2(4000),
  BUSINESS_COMPONENT_NAME VARCHAR2(4000),
  VARIABLE_EXPRESSION VARCHAR2(4000),
  VALIDATION_VALUE VARCHAR2(4000),
  LINKED_ITEM_NAME VARCHAR2(4000),
  BUSINESS_OBJECT_NAME VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  CONSTRAINT PK_LinkedItem PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_LinkedItem_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE Resources (
  ORIGINAL_ID VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  DOMAIN_SPECIFICATION VARCHAR2(4000),
  DATA_TYPE_CODE VARCHAR2(4000),
  INHERIT_FLAG VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  RESOURCE_NAME VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  CONSTRAINT PK_Resources PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_Resources_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE Script (
  PROGRAMMING_LANGUAGE VARCHAR2(4000),
  FIRST_VERS VARCHAR2(4000),
  ITEM_ID VARCHAR2(4000),
  ITEM_VERSION VARCHAR2(4000),
  SCRIPT_TEXT VARCHAR2(4000),
  SEQUENCE VARCHAR2(4000),
  ACTIVE_FLAG VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  ITEM_TYPE_CODE VARCHAR2(4000),
  LAST_VERS VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  SCRIPT_NAME VARCHAR2(4000),
  CONSTRAINT PK_Script PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_Script_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE ObjectAttribute (
  ROW_ID VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  DOMAIN_TYPE_CODE VARCHAR2(4000),
  UNIT_OF_MEASURE_CODE VARCHAR2(4000),
  REQUIRED_FLAG VARCHAR2(4000),
  MAXIMUM_VALUE VARCHAR2(4000),
  DEFAULT_VALUE VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  POST_PICK_CODE VARCHAR2(4000),
  VECTOR_FLAG VARCHAR2(4000),
  ASSET_FLAG VARCHAR2(4000),
  VALIDATION_SPECIFICATION VARCHAR2(4000),
  HIDDEN_FLAG VARCHAR2(4000),
  INCREMENT_VALUE VARCHAR2(4000),
  REJECT_VALUE VARCHAR2(4000),
  ELIGIBILITY_WORKFLOW_PROCEDURE_NAME VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  MINIMUM_VALUE VARCHAR2(4000),
  LOCAL_NAME VARCHAR2(4000),
  ATTRIBUTE_DEFINITION_ID VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  PARAMETRIC_SEARCH_FLAG VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  PRE_PICK_CODE VARCHAR2(4000),
  ATTRIBUTE_DEFINITION_VERSION VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  CONSTRAINT PK_ObjectAttribute PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_ObjectAttribute_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE ObjectAttributeTranslation (
  PARENT_ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  LOCAL_NAME VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  CONSTRAINT PK_ObjectAttributeTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE ConstraintRule (
  RULE_SPECIFICATION VARCHAR2(4000),
  NATURAL_LANGUAGE_SPECIFICATION VARCHAR2(4000),
  RULE_DESIGNER_ID VARCHAR2(4000),
  RULE_END_DATE VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  ACTIVE_FLAG VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  RULE_START_DATE VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  RULE_NAME VARCHAR2(4000),
  RULE_COMMENTS VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  CONSTRAINT PK_ConstraintRule PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_ConstraintRule_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE ConstraintRuleTranslation (
  LANGUAGE_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  CONSTRAINT PK_ConstraintRuleTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE UIOption (
  SEQUENCE_NUMBER VARCHAR2(4000),
  USER_INTERFACE_OPTION_CODE VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  USER_INTERFACE_OPTION_NAME VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  PRIMARY_RESPONSIBILITY_ID VARCHAR2(4000),
  USER_INTERFACE_CONTROL_STYLE_ID VARCHAR2(4000),
  USER_INTERFACE_FRAME_STYLE_ID VARCHAR2(4000),
  CONSTRAINT PK_UIOption PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_UIOption_VOD_ID UNIQUE (VOD_ID)
);
CREATE TABLE UIResponsibility (
  LAST_VERSION VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  USER_INTERFACE_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  RESPONSIBILITY_ID VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  CONSTRAINT PK_UIResponsibility PRIMARY KEY (ROW_ID)
);
CREATE TABLE UIGroup (
  ORIGINAL_ID VARCHAR2(4000),
  USER_INTERFACE_CONTROL_STYLE_ID VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  USER_INTERFACE_OPTION_ID VARCHAR2(4000),
  USER_INTERFACE_GROUP_NAME VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  LAST_UPDATED VARCHAR2(4000),
  CONSTRAINT PK_UIGroup PRIMARY KEY (ROW_ID)
);
CREATE TABLE UIGroupTranslation (
  ROW_ID VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  USER_INTERFACE_GROUP_NAME VARCHAR2(4000),
  CONSTRAINT PK_UIGroupTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE UIGroupItem (
  ITEM_TYPE_CODE VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  USER_INTERFACE_GROUP_ID VARCHAR2(4000),
  LAST_VERSION VARCHAR2(4000),
  USER_INTERFACE_CONTROL_STYLE_ID VARCHAR2(4000),
  FIRST_VERSION VARCHAR2(4000),
  ORIGINAL_ID VARCHAR2(4000),
  ITEM_NAME VARCHAR2(4000),
  ITEM_ID VARCHAR2(4000),
  PATH_SPECIFICATION VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  CONSTRAINT PK_UIGroupItem PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionMessages (
  PARENT_ROW_ID VARCHAR2(4000),
  REASON_TEXT VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  CONSTRAINT PK_PromotionMessages PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionItem (
  CHARGE_AMOUNT VARCHAR2(4000),
  RECOMMENDATION_FLAG VARCHAR2(4000),
  PROMOTION_ID VARCHAR2(4000),
  PRODUCT_PORT_ORIGIN_ID VARCHAR2(4000),
  PRODUCT_LINE_ID VARCHAR2(4000),
  APPLY_COMPONENT_CHARGE_FLAG VARCHAR2(4000),
  COMMIT_PERIOD VARCHAR2(4000),
  PRORATE_PLAN VARCHAR2(4000),
  DISCONNECT_ACTION_TYPE VARCHAR2(4000),
  DEFAULT_QUANTITY VARCHAR2(4000),
  PARENT_PROMOTION_ITEM_ID VARCHAR2(4000),
  PRODUCT_ID VARCHAR2(4000),
  CARDNALITY_MODIFICATION_FLAG VARCHAR2(4000),
  MAXIMUM_QUANTITY VARCHAR2(4000),
  SUB_OBJECT_VOD_NUMBER VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  PRODUCT_CLASS_VOD_NUMBER VARCHAR2(4000),
  CP_CONSTRAINT_MODIFICATION_FLAG VARCHAR2(4000),
  GRACE_PERIOD VARCHAR2(4000),
  DOMAIN_MODIFICATION_FLAG VARCHAR2(4000),
  ROOT_PROMOTION_ITEM_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  ITEM_NAME VARCHAR2(4000),
  DESCRIPTION_TEXT VARCHAR2(4000),
  MINIMUM_QUANTITY VARCHAR2(4000),
  EXTENDED_ATTRIBUTE_MODIFICATION_FLAG VARCHAR2(4000),
  COMMIT_COVERAGE_FLAG VARCHAR2(4000),
  DEFAULT_BILLING_ACCOUNT VARCHAR2(4000),
  DEFAULT_OWNER_ACCOUNT VARCHAR2(4000),
  DEFAULT_SERVICE_ACCOUNT VARCHAR2(4000),
  COMMIT_PERIOD_UNIT_OF_MEASURE VARCHAR2(4000),
  GRACE_PERIOD_UNIT_OF_MEASURE VARCHAR2(4000),
  TYPE_CODE VARCHAR2(4000),
  CONSTRAINT PK_PromotionItem PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_PromotionItem_PROMOTION_ID UNIQUE (PROMOTION_ID)
);
CREATE TABLE PromotionItemTranslation (
  DESCRIPTION_TEXT VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  LANGUAGE_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  CONSTRAINT PK_PromotionItemTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionItemXA (
  ATTRIBUTE_NAME VARCHAR2(4000),
  CONDITIONAL_ACTION_CODE VARCHAR2(4000),
  PROMOTION_ITEM_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  CONSTRAINT PK_PromotionItemXA PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionItemVal (
  ROW_ID VARCHAR2(4000),
  ATTRIBUTE_VALUE VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  CONSTRAINT PK_PromotionItemVal PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionCharge (
  ROW_ID VARCHAR2(4000),
  CHARGE_PERIOD VARCHAR2(4000),
  PROMOTION_ID VARCHAR2(4000),
  TYPE_CODE VARCHAR2(4000),
  PRORATE_PLAN_ID VARCHAR2(4000),
  GRACE_PERIOD_NUMBER VARCHAR2(4000),
  CHARGE_AMOUNT VARCHAR2(4000),
  CHARGE_AMOUNT_CURRENCY_CODE VARCHAR2(4000),
  GRACE_PERIOD_UNIT_OF_MEASURE VARCHAR2(4000),
  CHARGE_AMOUNT_EXCHANGE_DATE VARCHAR2(4000),
  CONSTRAINT PK_PromotionCharge PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_PromotionCharge_PROMOTION_ID UNIQUE (PROMOTION_ID)
);
CREATE TABLE PromotionMergeSplit (
  PENALTY_AMOUNT_EXCHANGE_DATE VARCHAR2(4000),
  PENALTY_AMOUNT VARCHAR2(4000),
  OPERATION_DESCRIPTION VARCHAR2(4000),
  PENALTY_AMOUNT_CURRENCY_CODE VARCHAR2(4000),
  OPERATION_NAME VARCHAR2(4000),
  DISPLAY_COMMITMENT_FLAG VARCHAR2(4000),
  DISPLAY_PRORATED_CHARGE_FLAG VARCHAR2(4000),
  PROMOTION_PRODUCT_ID VARCHAR2(4000),
  PRO_RATED_PLAN_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  AGGR_DURATION_CD VARCHAR2(4000),
  PROMOTION_OPERATION_TYPE VARCHAR2(4000),
  DURATION_CODE VARCHAR2(4000),
  COMMIT_START_CODE VARCHAR2(4000),
  CONSTRAINT PK_PromotionMergeSplit PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionMergeSplitComp (
  PENALTY_AMOUNT_EXCHANGE_DATE VARCHAR2(4000),
  DESCRIPTION_TEXT VARCHAR2(4000),
  PRODUCT_ID VARCHAR2(4000),
  COMMIT_START_CODE VARCHAR2(4000),
  PROMOTION_DURATION_CODE VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  MAXIMUM_QUANTITY VARCHAR2(4000),
  PENALTY_AMOUNT_CURRENCY_CODE VARCHAR2(4000),
  PENALTY_AMOUNT VARCHAR2(4000),
  PROMOTION_OPERATION_ID VARCHAR2(4000),
  MINIMUM_QUANTITY VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  PRORATE_PLAN VARCHAR2(4000),
  DEFAULT_QUANTITY VARCHAR2(4000),
  DISPLAY_PRORATED_CHARGE_FLAG VARCHAR2(4000),
  DISPLAY_COMMITMENT_FLAG VARCHAR2(4000),
  CONSTRAINT PK_PromotionMergeSplitComp PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionPricing (
  PRICING_TYPE_CODE VARCHAR2(4000),
  DISTRIBUTION_CHANNEL_CODE VARCHAR2(4000),
  DIVISION_CODE VARCHAR2(4000),
  PRICING_ADJUSTMENT_CODE VARCHAR2(4000),
  EFFECTIVE_START_DATE VARCHAR2(4000),
  EFFECTIVE_END_DATE VARCHAR2(4000),
  PROMOTION_GROUP_ID VARCHAR2(4000),
  PRODUCT_ID VARCHAR2(4000),
  PRODUCT_CLASS_VOD_NUMBER VARCHAR2(4000),
  PROMOTION_ID VARCHAR2(4000),
  CURRENCY_CODE VARCHAR2(4000),
  PROMOTION_GROUP_MEMBERSHIP_ID VARCHAR2(4000),
  MATRIX_RULE_NUMBER VARCHAR2(4000),
  EXCHANGE_DATE VARCHAR2(4000),
  SALES_ORGANIZATION_CODE VARCHAR2(4000),
  PRODUCT_LINE_ID VARCHAR2(4000),
  PRICING_ADJUSTMENT_VALUE VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  ADJUSTMENT_GROUP_ID VARCHAR2(4000),
  CONSTRAINT PK_PromotionPricing PRIMARY KEY (ROW_ID),
  CONSTRAINT UQ_PromotionPricing_PROMOTION_ID UNIQUE (PROMOTION_ID)
);
CREATE TABLE JointWorkspace (
  JOINT_WORKSPACE_NAME VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  STATUS_CODE VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  EFFECTIVE_RELEASE_TIMESTAMP VARCHAR2(4000),
  BASE_SYSTEM_TIMESTAMP VARCHAR2(4000),
  CONSTRAINT PK_JointWorkspace PRIMARY KEY (ROW_ID)
);
CREATE TABLE JointWorkspaceTranslation (
  LANGUAGE_ID VARCHAR2(4000),
  PARENT_ROW_ID VARCHAR2(4000),
  JOINT_WORKSPACE_NAME VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  CONSTRAINT PK_JointWorkspaceTranslation PRIMARY KEY (ROW_ID)
);
CREATE TABLE JointWorkspaceItem (
  ROW_ID VARCHAR2(4000),
  JOINT_WORKSPACE_ID VARCHAR2(4000),
  VOD_ID VARCHAR2(4000),
  VERSIONED_OBJECT_DEFINITION_STATUS_CODE VARCHAR2(4000),
  VERSIONED_OBJECT_DEFINITION_VERSION VARCHAR2(4000),
  CONSTRAINT PK_JointWorkspaceItem PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionUpgrade (
  DISPLAY_COMMITMENT_FLAG VARCHAR2(4000),
  PARENT_PRODUCT_ID VARCHAR2(4000),
  COMMIT_START_CODE VARCHAR2(4000),
  DURATION_CODE VARCHAR2(4000),
  VALIDATION_STATUS_CODE VARCHAR2(4000),
  RELATION_TYPE VARCHAR2(4000),
  SERVICE_CHARGE_TYPES VARCHAR2(4000),
  PRODUCT_CLASS_VOD_NUMBER VARCHAR2(4000),
  UPGRADE_OFFER_DESCRIPTION VARCHAR2(4000),
  PACKAGE_MANUAL_ALLOCATION_AMOUNT VARCHAR2(4000),
  LINE_NUMBER VARCHAR2(4000),
  PORTFOLIO_PERCENT VARCHAR2(4000),
  OPTION_FLAG VARCHAR2(4000),
  PRODUCT_LINE_ID VARCHAR2(4000),
  DISPLAY_PRORATED_CHARGE_FLAG VARCHAR2(4000),
  PERCENT_TO_SELL VARCHAR2(4000),
  SPLIT_MENU_PRICING_FLAG VARCHAR2(4000),
  PRODUCT_ID VARCHAR2(4000),
  DISPLAY_COMPONENT_PRICE_FLAG VARCHAR2(4000),
  EFF_END_DATE VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  PENALTY_AMOUNT_EXCHANGE_DATE VARCHAR2(4000),
  PRORATE_PLAN_ID VARCHAR2(4000),
  PENALTY_AMOUNT VARCHAR2(4000),
  EFF_START_DT VARCHAR2(4000),
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  DISPLAY_COMPONENT_FLAG VARCHAR2(4000),
  QUANTITY VARCHAR2(4000),
  DOCKING_NUMBER VARCHAR2(4000),
  PENALTY_AMOUNT_CURRENCY_CODE VARCHAR2(4000),
  MENU_COURSE_NUMBER VARCHAR2(4000),
  REPORT_SEQUENCE_NUMBER VARCHAR2(4000),
  SPLIT_MENU_PRICE VARCHAR2(4000),
  CONSTRAINT PK_PromotionUpgrade PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionConfigItem (
  CURCY_CD VARCHAR2(4000),
  PRO_ADJ_TYPE_CD VARCHAR2(4000),
  PRO_LST_ITEM_ID VARCHAR2(4000),
  PROD_ID VARCHAR2(4000),
  PAR_ITEM_ORIG_ID VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  PROMOTION_NUMBER VARCHAR2(4000),
  ADJ_VAL_AMT VARCHAR2(4000),
  PROMOTION_GROUP_ID VARCHAR2(4000),
  PROMOTION_GROUP_MEMBERSHIP_ID VARCHAR2(4000),
  DOCKING_NUMBER VARCHAR2(4000),
  EFF_END_DT VARCHAR2(4000),
  EFF_START_DT VARCHAR2(4000),
  MAX_PRI VARCHAR2(4000),
  MIN_PRI VARCHAR2(4000),
  EXCH_DT VARCHAR2(4000),
  LAST_UPDATED_ON VARCHAR2(4000),
  CONSTRAINT PK_PromotionConfigItem PRIMARY KEY (ROW_ID)
);
CREATE TABLE PromotionTerm (
  DESCRIPTIVE_TEXT VARCHAR2(4000),
  TYPE_CODE VARCHAR2(4000),
  ROW_ID VARCHAR2(4000),
  TERM_TEMPLATE_ID VARCHAR2(4000),
  SEQUENCE_NUMBER VARCHAR2(4000),
  PRODUCT_ID VARCHAR2(4000),
  NAME VARCHAR2(4000),
  ASSOCIATE_PRODUCT_ID VARCHAR2(4000),
  SECTION_NUMBER VARCHAR2(4000),
  CONSTRAINT PK_PromotionTerm PRIMARY KEY (ROW_ID)
);
ALTER TABLE AttributeVod ADD CONSTRAINT FK_AttributeVod_ROW_ID_TO_VodVersion_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES VodVersion (VOD_ID);
ALTER TABLE AttributeVod ADD CONSTRAINT FK_AttributeVod_ROW_ID_TO_AttributeDefinition_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES AttributeDefinition (VOD_ID);
ALTER TABLE AttributeVod ADD CONSTRAINT FK_AttributeVod_ROW_ID_TO_AttributeValue_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES AttributeValue (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_VodVersion_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES VodVersion (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_ObjectDefinition_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectDefinition (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_ObjectRelationship_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectRelationship (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_ObjectUIProperty_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectUIProperty (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_LinkedItem_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES LinkedItem (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_Resources_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES Resources (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_Script_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES Script (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_ObjectAttribute_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectAttribute (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_ConstraintRule_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ConstraintRule (VOD_ID);
ALTER TABLE ClassVod ADD CONSTRAINT FK_ClassVod_ROW_ID_TO_UIOption_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES UIOption (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_VodVersion_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES VodVersion (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_ObjectDefinition_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectDefinition (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_ObjectRelationship_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectRelationship (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_ObjectUIProperty_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectUIProperty (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_LinkedItem_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES LinkedItem (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_Resources_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES Resources (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_Script_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES Script (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_ObjectAttribute_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ObjectAttribute (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_ConstraintRule_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES ConstraintRule (VOD_ID);
ALTER TABLE ProductVod ADD CONSTRAINT FK_ProductVod_ROW_ID_TO_UIOption_VOD_ID FOREIGN KEY (ROW_ID) REFERENCES UIOption (VOD_ID);
ALTER TABLE JointWorkspaceItem ADD CONSTRAINT FK_JointWorkspaceItem_VOD_ID_TO_AttributeVod_ROW_ID FOREIGN KEY (VOD_ID) REFERENCES AttributeVod (ROW_ID);
ALTER TABLE JointWorkspaceItem ADD CONSTRAINT FK_JointWorkspaceItem_VOD_ID_TO_ClassVod_ROW_ID FOREIGN KEY (VOD_ID) REFERENCES ClassVod (ROW_ID);
ALTER TABLE JointWorkspaceItem ADD CONSTRAINT FK_JointWorkspaceItem_VOD_ID_TO_ProductVod_ROW_ID FOREIGN KEY (VOD_ID) REFERENCES ProductVod (ROW_ID);
ALTER TABLE PromotionDefinition ADD CONSTRAINT FK_PromotionDefinition_ROW_ID_TO_PromotionItem_PROMOTION_ID FOREIGN KEY (ROW_ID) REFERENCES PromotionItem (PROMOTION_ID);
ALTER TABLE PromotionDefinition ADD CONSTRAINT FK_PromotionDefinition_ROW_ID_TO_PromotionCharge_PROMOTION_ID FOREIGN KEY (ROW_ID) REFERENCES PromotionCharge (PROMOTION_ID);
ALTER TABLE PromotionDefinition ADD CONSTRAINT FK_PromotionDefinition_ROW_ID_TO_PromotionPricing_PROMOTION_ID FOREIGN KEY (ROW_ID) REFERENCES PromotionPricing (PROMOTION_ID);
ALTER TABLE PromotionConfigItem ADD CONSTRAINT FK_PromotionConfigItem_PROD_ID_TO_ProductDefinition_ROW_ID FOREIGN KEY (PROD_ID) REFERENCES ProductDefinition (ROW_ID);