CREATE PROPERTY GRAPH "test_graph" 
 VERTEX TABLES (
"ATTRIBUTEVOD" 
  KEY ("ROW_ID") 
  PROPERTIES ("VOD_TYPE", "VOD_NAME", "ROW_ID", "DESCRIPTIVE_TEXT", "LOCKED_FLAG", "OBJECT_NUMBER", "LAST_UPDATED_ON"),
"CLASSVOD" 
  KEY ("ROW_ID") 
  PROPERTIES ("VOD_TYPE", "VOD_NAME", "ROW_ID", "DESCRIPTIVE_TEXT", "LOCKED_FLAG", "OBJECT_NUMBER", "LAST_UPDATED_ON"),
"PRODUCTVOD" 
  KEY ("ROW_ID") 
  PROPERTIES ("VOD_TYPE", "VOD_NAME", "ROW_ID", "DESCRIPTIVE_TEXT", "LOCKED_FLAG", "OBJECT_NUMBER", "LAST_UPDATED_ON"),
"VODTRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("VOD_NAME", "LANGUAGE_ID", "PARENT_ROW_ID", "ROW_ID", "DESCRIPTIVE_TEXT", "LAST_UPDATED_ON"),
"VODVERSION" 
  KEY ("ROW_ID") 
  PROPERTIES ("VERSION_NUMBER", "VERSION_ID", "VOD_ID", "START_DATE", "CURRENT_VERSION_FLAG", "DESCRIPTIVE_TEXT", "END_DATE", "RELEASED_FLAG", "ROW_ID", "ACTIVE_FLAG", "LAST_UPDATED_ON"),
"ATTRIBUTEDEFINITION" 
  KEY ("ROW_ID") 
  PROPERTIES ("FIRST_VERSION", "VOD_ID", "ORIGINAL_ID", "ROW_ID", "MINIMUM_VALUE", "INCREMENT_VALUE", "UNIT_OF_MEASURE_CODE", "DATA_TYPE_CODE", "DOMAIN_TYPE_CODE", "LAST_VERSION", "MAXIMUM_VALUE", "LAST_UPDATED_ON"),
"ATTRIBUTEVALUE" 
  KEY ("ROW_ID") 
  PROPERTIES ("ORIGINAL_ID", "ACTIVE_FLAG", "LANGUAGE_INDEPENDENT_CODE_VALUE", "LAST_VERSION", "VOD_ID", "FIRST_VERSION", "ROW_ID", "SEQUENCE_NUMBER", "LAST_UPDATED_ON"),
"ATTRIBUTEVALUETRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("ROW_ID", "PARENT_ROW_ID", "LANGUAGE_INDEPENDENT_CODE_VALUE", "LANGUAGE_ID", "LAST_UPDATED_ON"),
"PRODUCTDEFINITION" 
  KEY ("ROW_ID") 
  PROPERTIES ("ALIAS_NAME", "BILLABLE_FLAG", "ACTIVE_FLAG", "NAME", "FULFILLMENT_ITEM_CODE", "CONFIGURATION_MODEL_ID", "PRIMARY_PRODUCT_LINE", "PRIMARY_POSITION", "BUSINESS_UNIT_ID", "EFFECTIVE_START_DATE", "CURCY_CD", "DESCRIPTIVE_TEXT", "ROW_ID", "EFFECTIVE_END_DATE", "PART_NUMBER", "VERSION", "STATUS", "TYPE", "INTEGRATION_PRODUCT_TYPE", "PRODUCT_CODE", "PRODUCT_TYPE_CODE", "PROMOTION_INSTANCE_CODE", "PROMOTION_TYPE_CODE", "UNIT_OF_MEASURE_CODE", "PRICE_TYPE_CD", "LAST_UPDATED_ON"),
"PROMOTIONDEFINITION" 
  KEY ("ROW_ID") 
  PROPERTIES ("ALIAS_NAME", "BILLABLE_FLAG", "ACTIVE_FLAG", "NAME", "FULFILLMENT_ITEM_CODE", "CONFIGURATION_MODEL_ID", "PRIMARY_PRODUCT_LINE", "PRIMARY_POSITION", "BUSINESS_UNIT_ID", "EFFECTIVE_START_DATE", "CURCY_CD", "DESCRIPTIVE_TEXT", "ROW_ID", "EFFECTIVE_END_DATE", "PART_NUMBER", "VERSION", "STATUS", "TYPE", "INTEGRATION_PRODUCT_TYPE", "PRODUCT_CODE", "PRODUCT_TYPE_CODE", "PROMOTION_INSTANCE_CODE", "PROMOTION_TYPE_CODE", "UNIT_OF_MEASURE_CODE", "PRICE_TYPE_CD", "LAST_UPDATED_ON"),
"OBJECTDEFINITION" 
  KEY ("ROW_ID") 
  PROPERTIES ("PARENT_VOD_VERSION", "POST_PICK_CODE", "ORIGINAL_ID", "ROW_ID", "FIRST_VERSION", "LAST_VERSION", "PARENT_VOD_ID", "VOD_ID", "DESCRIPTIVE_TEXT", "PRE_PICK_CODE", "SMART_PART_NUMBER_DEFINITION_ID", "OBJECT_NAME", "LAST_UPDATED_ON"),
"OBJECTDEFINITIONTRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("ROW_ID", "PARENT_ROW_ID", "DESCRIPTIVE_TEXT", "OBJECT_NAME", "LANGUAGE_ID", "LAST_UPDATED_ON"),
"OBJECTRELATIONSHIP" 
  KEY ("ROW_ID") 
  PROPERTIES ("RELATIONSHIP_TYPE_CODE", "DISPLAY_COMPONENT_FLAG", "SEQUENCE_NUMBER", "FIRST_VERSION", "VOD_ID", "ROW_ID", "DEFAULT_QUANTITY", "SUB_OBJECT_CLASS_ID", "SUB_OBJECT_PRODUCT_ID", "PARENT_RELATIONSHIP_ID", "RELATIONSHIP_NAME", "DEFAULT_SUB_OBJECT_PRODUCT_ID", "OPTION_FLAG", "DESCRIPTIVE_TEXT", "LAST_VERSION", "MINIMUM_QUANTITY", "FORECAST_FLAG", "SUB_OBJECT_PRODUCT_VERSION", "DISPLAY_COMPONENT_PRICE_FLAG", "MAXIMUM_QUANTITY", "SUB_OBJECT_CLASS_VERSION", "ORIGINAL_ID", "SUB_OBJECT_TYPE_CODE", "LAST_UPDATED_ON"),
"OBJECTRELATIONSHIPDOMAIN" 
  KEY ("ROW_ID") 
  PROPERTIES ("RELATIONSHIP_TYPE_CODE", "DISPLAY_COMPONENT_FLAG", "SEQUENCE_NUMBER", "FIRST_VERSION", "VOD_ID", "ROW_ID", "DEFAULT_QUANTITY", "SUB_OBJECT_CLASS_ID", "SUB_OBJECT_PRODUCT_ID", "PARENT_RELATIONSHIP_ID", "RELATIONSHIP_NAME", "DEFAULT_SUB_OBJECT_PRODUCT_ID", "OPTION_FLAG", "DESCRIPTIVE_TEXT", "LAST_VERSION", "MINIMUM_QUANTITY", "FORECAST_FLAG", "SUB_OBJECT_PRODUCT_VERSION", "DISPLAY_COMPONENT_PRICE_FLAG", "MAXIMUM_QUANTITY", "SUB_OBJECT_CLASS_VERSION", "ORIGINAL_ID", "LAST_UPDATED_ON"),
"OBJECTRELATIONSHIPTRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("LANGUAGE_ID", "PARENT_ROW_ID", "ROW_ID", "RELATIONSHIP_NAME", "LAST_UPDATED_ON"),
"OBJECTUIPROPERTY" 
  KEY ("ROW_ID") 
  PROPERTIES ("PROPERTY_TYPE_CD", "ITEM_VALUE_SPECIFICATION", "FIRST_VERSION", "ITEM_DEFINITION", "LAST_VERSION", "VOD_ID", "PROPERTY_NAME", "ROW_ID", "ORIGINAL_ID", "ITEM_TYPE_CODE", "LAST_UPDATED_ON"),
"OBJECTUIPROPERTYTRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("PARENT_ROW_ID", "ITEM_VALUE_SPECIFICATION", "ROW_ID", "LANGUAGE_ID", "LAST_UPDATED_ON"),
"LINKEDITEM" 
  KEY ("ROW_ID") 
  PROPERTIES ("SYSTEM_KEYWORD_CODE", "DEFAULT_VALUE", "VARIABLE_NAME", "LAST_VERSION", "EXEC_FLG", "SORT_SPECIFICATION", "SEARCH_SPECIFICATION", "ACTIVE_FLG", "ROW_ID", "FIRST_VERSION", "FIELD_NAME", "BUSINESS_COMPONENT_NAME", "VARIABLE_EXPRESSION", "VALIDATION_VALUE", "LINKED_ITEM_NAME", "BUSINESS_OBJECT_NAME", "DESCRIPTIVE_TEXT", "ORIGINAL_ID", "VOD_ID", "LAST_UPDATED_ON"),
"RESOURCES" 
  KEY ("ROW_ID") 
  PROPERTIES ("ORIGINAL_ID", "VOD_ID", "DOMAIN_SPECIFICATION", "DATA_TYPE_CODE", "INHERIT_FLAG", "FIRST_VERSION", "DESCRIPTIVE_TEXT", "RESOURCE_NAME", "ROW_ID", "LAST_VERSION", "LAST_UPDATED_ON"),
"SCRIPT" 
  KEY ("ROW_ID") 
  PROPERTIES ("PROGRAMMING_LANGUAGE", "FIRST_VERS", "ITEM_ID", "ITEM_VERSION", "SCRIPT_TEXT", "SEQUENCE", "ACTIVE_FLAG", "DESCRIPTIVE_TEXT", "ITEM_TYPE_CODE", "LAST_VERS", "VOD_ID", "ORIGINAL_ID", "ROW_ID", "SCRIPT_NAME", "LAST_UPDATED_ON"),
"OBJECTATTRIBUTE" 
  KEY ("ROW_ID") 
  PROPERTIES ("ROW_ID", "VOD_ID", "DOMAIN_TYPE_CODE", "UNIT_OF_MEASURE_CODE", "REQUIRED_FLAG", "MAXIMUM_VALUE", "DEFAULT_VALUE", "FIRST_VERSION", "POST_PICK_CODE", "VECTOR_FLAG", "ASSET_FLAG", "VALIDATION_SPECIFICATION", "HIDDEN_FLAG", "INCREMENT_VALUE", "REJECT_VALUE", "ELIGIBILITY_WORKFLOW_PROCEDURE_NAME", "DESCRIPTIVE_TEXT", "MINIMUM_VALUE", "LOCAL_NAME", "ATTRIBUTE_DEFINITION_ID", "SEQUENCE_NUMBER", "PARAMETRIC_SEARCH_FLAG", "ORIGINAL_ID", "PRE_PICK_CODE", "ATTRIBUTE_DEFINITION_VERSION", "LAST_VERSION", "LAST_UPDATED_ON"),
"OBJECTATTRIBUTETRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("PARENT_ROW_ID", "DESCRIPTIVE_TEXT", "LOCAL_NAME", "ROW_ID", "LANGUAGE_ID", "LAST_UPDATED_ON"),
"CONSTRAINTRULE" 
  KEY ("ROW_ID") 
  PROPERTIES ("RULE_SPECIFICATION", "NATURAL_LANGUAGE_SPECIFICATION", "RULE_DESIGNER_ID", "RULE_END_DATE", "FIRST_VERSION", "ACTIVE_FLAG", "ORIGINAL_ID", "DESCRIPTIVE_TEXT", "RULE_START_DATE", "VOD_ID", "RULE_NAME", "RULE_COMMENTS", "ROW_ID", "LAST_VERSION", "LAST_UPDATED_ON"),
"CONSTRAINTRULETRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("LANGUAGE_ID", "ROW_ID", "DESCRIPTIVE_TEXT", "PARENT_ROW_ID", "LAST_UPDATED_ON"),
"UIOPTION" 
  KEY ("ROW_ID") 
  PROPERTIES ("SEQUENCE_NUMBER", "USER_INTERFACE_OPTION_CODE", "VOD_ID", "ORIGINAL_ID", "USER_INTERFACE_OPTION_NAME", "DESCRIPTIVE_TEXT", "LAST_VERSION", "ROW_ID", "FIRST_VERSION", "PRIMARY_RESPONSIBILITY_ID", "USER_INTERFACE_CONTROL_STYLE_ID", "USER_INTERFACE_FRAME_STYLE_ID", "LAST_UPDATED_ON"),
"UIRESPONSIBILITY" 
  KEY ("ROW_ID") 
  PROPERTIES ("LAST_VERSION", "VOD_ID", "USER_INTERFACE_ID", "ROW_ID", "FIRST_VERSION", "RESPONSIBILITY_ID", "ORIGINAL_ID", "LAST_UPDATED_ON"),
"UIGROUP" 
  KEY ("ROW_ID") 
  PROPERTIES ("ORIGINAL_ID", "USER_INTERFACE_CONTROL_STYLE_ID", "SEQUENCE_NUMBER", "LAST_VERSION", "DESCRIPTIVE_TEXT", "VOD_ID", "ROW_ID", "USER_INTERFACE_OPTION_ID", "USER_INTERFACE_GROUP_NAME", "FIRST_VERSION", "LAST_UPDATED_ON"),
"UIGROUPTRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("ROW_ID", "PARENT_ROW_ID", "LANGUAGE_ID", "USER_INTERFACE_GROUP_NAME", "LAST_UPDATED_ON"),
"UIGROUPITEM" 
  KEY ("ROW_ID") 
  PROPERTIES ("ITEM_TYPE_CODE", "ROW_ID", "SEQUENCE_NUMBER", "USER_INTERFACE_GROUP_ID", "LAST_VERSION", "USER_INTERFACE_CONTROL_STYLE_ID", "FIRST_VERSION", "ORIGINAL_ID", "ITEM_NAME", "ITEM_ID", "PATH_SPECIFICATION", "VOD_ID", "LAST_UPDATED_ON"),
"PROMOTIONMESSAGES" 
  KEY ("ROW_ID") 
  PROPERTIES ("PARENT_ROW_ID", "REASON_TEXT", "LANGUAGE_ID", "ROW_ID", "DESCRIPTIVE_TEXT", "LAST_UPDATED_ON"),
"PROMOTIONITEM" 
  KEY ("ROW_ID") 
  PROPERTIES ("CHARGE_AMOUNT", "RECOMMENDATION_FLAG", "PROMOTION_ID", "PRODUCT_PORT_ORIGIN_ID", "PRODUCT_LINE_ID", "APPLY_COMPONENT_CHARGE_FLAG", "COMMIT_PERIOD", "PRORATE_PLAN", "DISCONNECT_ACTION_TYPE", "DEFAULT_QUANTITY", "PARENT_PROMOTION_ITEM_ID", "PRODUCT_ID", "CARDNALITY_MODIFICATION_FLAG", "MAXIMUM_QUANTITY", "SUB_OBJECT_VOD_NUMBER", "SEQUENCE_NUMBER", "PRODUCT_CLASS_VOD_NUMBER", "CP_CONSTRAINT_MODIFICATION_FLAG", "GRACE_PERIOD", "DOMAIN_MODIFICATION_FLAG", "ROOT_PROMOTION_ITEM_ID", "ROW_ID", "ITEM_NAME", "DESCRIPTION_TEXT", "MINIMUM_QUANTITY", "EXTENDED_ATTRIBUTE_MODIFICATION_FLAG", "COMMIT_COVERAGE_FLAG", "DEFAULT_BILLING_ACCOUNT", "DEFAULT_OWNER_ACCOUNT", "DEFAULT_SERVICE_ACCOUNT", "COMMIT_PERIOD_UNIT_OF_MEASURE", "GRACE_PERIOD_UNIT_OF_MEASURE", "TYPE_CODE", "LAST_UPDATED_ON"),
"PROMOTIONITEMTRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("DESCRIPTION_TEXT", "PARENT_ROW_ID", "LANGUAGE_ID", "ROW_ID", "LAST_UPDATED_ON"),
"PROMOTIONITEMXA" 
  KEY ("ROW_ID") 
  PROPERTIES ("ATTRIBUTE_NAME", "CONDITIONAL_ACTION_CODE", "PROMOTION_ITEM_ID", "ROW_ID", "LAST_UPDATED_ON"),
"PROMOTIONITEMVAL" 
  KEY ("ROW_ID") 
  PROPERTIES ("ROW_ID", "ATTRIBUTE_VALUE", "PARENT_ROW_ID", "LAST_UPDATED_ON"),
"PROMOTIONCHARGE" 
  KEY ("ROW_ID") 
  PROPERTIES ("ROW_ID", "CHARGE_PERIOD", "PROMOTION_ID", "TYPE_CODE", "PRORATE_PLAN_ID", "GRACE_PERIOD_NUMBER", "CHARGE_AMOUNT", "CHARGE_AMOUNT_CURRENCY_CODE", "GRACE_PERIOD_UNIT_OF_MEASURE", "CHARGE_AMOUNT_EXCHANGE_DATE", "LAST_UPDATED_ON"),
"PROMOTIONMERGESPLIT" 
  KEY ("ROW_ID") 
  PROPERTIES ("PENALTY_AMOUNT_EXCHANGE_DATE", "PENALTY_AMOUNT", "OPERATION_DESCRIPTION", "PENALTY_AMOUNT_CURRENCY_CODE", "OPERATION_NAME", "DISPLAY_COMMITMENT_FLAG", "DISPLAY_PRORATED_CHARGE_FLAG", "PROMOTION_PRODUCT_ID", "PRO_RATED_PLAN_ID", "ROW_ID", "AGGR_DURATION_CD", "PROMOTION_OPERATION_TYPE", "DURATION_CODE", "COMMIT_START_CODE", "LAST_UPDATED_ON"),
"PROMOTIONMERGESPLITCOMP" 
  KEY ("ROW_ID") 
  PROPERTIES ("PENALTY_AMOUNT_EXCHANGE_DATE", "DESCRIPTION_TEXT", "PRODUCT_ID", "COMMIT_START_CODE", "PROMOTION_DURATION_CODE", "SEQUENCE_NUMBER", "MAXIMUM_QUANTITY", "PENALTY_AMOUNT_CURRENCY_CODE", "PENALTY_AMOUNT", "PROMOTION_OPERATION_ID", "MINIMUM_QUANTITY", "ROW_ID", "PRORATE_PLAN", "DEFAULT_QUANTITY", "DISPLAY_PRORATED_CHARGE_FLAG", "DISPLAY_COMMITMENT_FLAG", "LAST_UPDATED_ON"),
"PROMOTIONPRICING" 
  KEY ("ROW_ID") 
  PROPERTIES ("PRICING_TYPE_CODE", "DISTRIBUTION_CHANNEL_CODE", "DIVISION_CODE", "PRICING_ADJUSTMENT_CODE", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "PROMOTION_GROUP_ID", "PRODUCT_ID", "PRODUCT_CLASS_VOD_NUMBER", "PROMOTION_ID", "CURRENCY_CODE", "PROMOTION_GROUP_MEMBERSHIP_ID", "MATRIX_RULE_NUMBER", "EXCHANGE_DATE", "SALES_ORGANIZATION_CODE", "PRODUCT_LINE_ID", "PRICING_ADJUSTMENT_VALUE", "ROW_ID", "ADJUSTMENT_GROUP_ID", "LAST_UPDATED_ON"),
"JOINTWORKSPACE" 
  KEY ("ROW_ID") 
  PROPERTIES ("JOINT_WORKSPACE_NAME", "DESCRIPTIVE_TEXT", "STATUS_CODE", "ROW_ID", "EFFECTIVE_RELEASE_TIMESTAMP", "BASE_SYSTEM_TIMESTAMP", "LAST_UPDATED_ON"),
"JOINTWORKSPACETRANSLATION" 
  KEY ("ROW_ID") 
  PROPERTIES ("LANGUAGE_ID", "PARENT_ROW_ID", "JOINT_WORKSPACE_NAME", "DESCRIPTIVE_TEXT", "ROW_ID", "LAST_UPDATED_ON"),
"JOINTWORKSPACEITEM" 
  KEY ("ROW_ID") 
  PROPERTIES ("ROW_ID", "JOINT_WORKSPACE_ID", "VOD_ID", "VERSIONED_OBJECT_DEFINITION_STATUS_CODE", "VERSIONED_OBJECT_DEFINITION_VERSION", "LAST_UPDATED_ON"),
"PROMOTIONUPGRADE" 
  KEY ("ROW_ID") 
  PROPERTIES ("DISPLAY_COMMITMENT_FLAG", "PARENT_PRODUCT_ID", "COMMIT_START_CODE", "DURATION_CODE", "VALIDATION_STATUS_CODE", "RELATION_TYPE", "SERVICE_CHARGE_TYPES", "PRODUCT_CLASS_VOD_NUMBER", "UPGRADE_OFFER_DESCRIPTION", "PACKAGE_MANUAL_ALLOCATION_AMOUNT", "LINE_NUMBER", "PORTFOLIO_PERCENT", "OPTION_FLAG", "PRODUCT_LINE_ID", "DISPLAY_PRORATED_CHARGE_FLAG", "PERCENT_TO_SELL", "SPLIT_MENU_PRICING_FLAG", "PRODUCT_ID", "DISPLAY_COMPONENT_PRICE_FLAG", "EFF_END_DATE", "ROW_ID", "PENALTY_AMOUNT_EXCHANGE_DATE", "PRORATE_PLAN_ID", "PENALTY_AMOUNT", "EFF_START_DT", "DESCRIPTIVE_TEXT", "DISPLAY_COMPONENT_FLAG", "QUANTITY", "DOCKING_NUMBER", "PENALTY_AMOUNT_CURRENCY_CODE", "MENU_COURSE_NUMBER", "REPORT_SEQUENCE_NUMBER", "SPLIT_MENU_PRICE", "LAST_UPDATED_ON"),
"PROMOTIONCONFIGITEM" 
  KEY ("ROW_ID") 
  PROPERTIES ("CURCY_CD", "PRO_ADJ_TYPE_CD", "PRO_LST_ITEM_ID", "PROD_ID", "PAR_ITEM_ORIG_ID", "ROW_ID", "PROMOTION_NUMBER", "ADJ_VAL_AMT", "PROMOTION_GROUP_ID", "PROMOTION_GROUP_MEMBERSHIP_ID", "DOCKING_NUMBER", "EFF_END_DT", "EFF_START_DT", "MAX_PRI", "MIN_PRI", "EXCH_DT", "LAST_UPDATED_ON"),
"PROMOTIONTERM" 
  KEY ("ROW_ID") 
  PROPERTIES ("DESCRIPTIVE_TEXT", "TYPE_CODE", "ROW_ID", "TERM_TEMPLATE_ID", "SEQUENCE_NUMBER", "PRODUCT_ID", "NAME", "ASSOCIATE_PRODUCT_ID", "SECTION_NUMBER", "LAST_UPDATED_ON")
  )
EDGE TABLES (
"ATTRIBUTEVOD" AS "ATTRIBUTEVOD_HAS_TRANSLATION_VODTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "ATTRIBUTEVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "VODTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_TRANSLATION_VODTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "VODTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_TRANSLATION_VODTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "VODTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"ATTRIBUTEVOD" AS "ATTRIBUTEVOD_HAS_VERSION_VODVERSION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "ATTRIBUTEVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "VODVERSION" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_VERSION_VODVERSION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "VODVERSION" ("VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_VERSION_VODVERSION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "VODVERSION" ("VOD_ID") 
NO PROPERTIES,
"ATTRIBUTEVOD" AS "ATTRIBUTEVOD_HAS_DETAIL_ATTRIBUTEDEFINITION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "ATTRIBUTEVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "ATTRIBUTEDEFINITION" ("VOD_ID") 
NO PROPERTIES,
"ATTRIBUTEVOD" AS "ATTRIBUTEVOD_HAS_VALUE_ATTRIBUTEVALUE" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "ATTRIBUTEVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "ATTRIBUTEVALUE" ("VOD_ID") 
NO PROPERTIES,
"ATTRIBUTEVALUE" AS "ATTRIBUTEVALUE_HAS_TRANSLATION_ATTRIBUTEVALUETRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "ATTRIBUTEVALUE" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "ATTRIBUTEVALUETRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_DEFINITION_PRODUCTDEFINITION" 
KEY ("OBJECT_NUMBER") 
SOURCE KEY ("OBJECT_NUMBER") REFERENCES "PRODUCTVOD" ("OBJECT_NUMBER") 
DESTINATION  KEY ("OBJECT_NUMBER") REFERENCES "PRODUCTDEFINITION" ("CONFIGURATION_MODEL_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_DEFINITION_PROMOTIONDEFINITION" 
KEY ("OBJECT_NUMBER") 
SOURCE KEY ("OBJECT_NUMBER") REFERENCES "PRODUCTVOD" ("OBJECT_NUMBER") 
DESTINATION  KEY ("OBJECT_NUMBER") REFERENCES "PROMOTIONDEFINITION" ("CONFIGURATION_MODEL_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_DEFINITION_OBJECTDEFINITION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTDEFINITION" ("VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_DEFINITION_OBJECTDEFINITION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTDEFINITION" ("VOD_ID") 
NO PROPERTIES,
"OBJECTDEFINITION" AS "OBJECTDEFINITION_HAS_TRANSLATION_OBJECTDEFINITIONTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "OBJECTDEFINITION" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTDEFINITIONTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"OBJECTDEFINITION" AS "OBJECTDEFINITION_REFERS_TO_CLASSVOD" 
KEY ("PARENT_VOD_ID") 
SOURCE KEY ("PARENT_VOD_ID") REFERENCES "OBJECTDEFINITION" ("PARENT_VOD_ID") 
DESTINATION  KEY ("PARENT_VOD_ID") REFERENCES "CLASSVOD" ("OBJECT_NUMBER") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_RELATIONSHIP_OBJECTRELATIONSHIP" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTRELATIONSHIP" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_RELATIONSHIP_OBJECTRELATIONSHIP" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTRELATIONSHIP" ("VOD_ID") 
NO PROPERTIES,
"OBJECTRELATIONSHIP" AS "OBJECTRELATIONSHIP_HAS_RELATIONSHIP_DOMAIN_OBJECTRELATIONSHIPDOMAIN" 
KEY ("ORIGINAL_ID") 
SOURCE KEY ("ORIGINAL_ID") REFERENCES "OBJECTRELATIONSHIP" ("ORIGINAL_ID") 
DESTINATION  KEY ("ORIGINAL_ID") REFERENCES "OBJECTRELATIONSHIPDOMAIN" ("PARENT_RELATIONSHIP_ID") 
NO PROPERTIES,
"OBJECTRELATIONSHIP" AS "OBJECTRELATIONSHIP_REFERS_TO_CLASSVOD" 
KEY ("SUB_OBJECT_CLASS_ID") 
SOURCE KEY ("SUB_OBJECT_CLASS_ID") REFERENCES "OBJECTRELATIONSHIP" ("SUB_OBJECT_CLASS_ID") 
DESTINATION  KEY ("SUB_OBJECT_CLASS_ID") REFERENCES "CLASSVOD" ("OBJECT_NUMBER") 
NO PROPERTIES,
"OBJECTRELATIONSHIP" AS "PRODUCTRELATION_REFERS_TO_PRODUCTVOD" 
KEY ("SUB_OBJECT_PRODUCT_ID") 
SOURCE KEY ("SUB_OBJECT_PRODUCT_ID") REFERENCES "OBJECTRELATIONSHIP" ("SUB_OBJECT_PRODUCT_ID") 
DESTINATION  KEY ("SUB_OBJECT_PRODUCT_ID") REFERENCES "PRODUCTVOD" ("OBJECT_NUMBER") 
NO PROPERTIES,
"OBJECTRELATIONSHIP" AS "DEFAULTPRODUCT_REFERS_TO_PRODUCTVOD" 
KEY ("DEFAULT_SUB_OBJECT_PRODUCT_ID") 
SOURCE KEY ("DEFAULT_SUB_OBJECT_PRODUCT_ID") REFERENCES "OBJECTRELATIONSHIP" ("DEFAULT_SUB_OBJECT_PRODUCT_ID") 
DESTINATION  KEY ("DEFAULT_SUB_OBJECT_PRODUCT_ID") REFERENCES "PRODUCTVOD" ("OBJECT_NUMBER") 
NO PROPERTIES,
"OBJECTRELATIONSHIPDOMAIN" AS "OBJECTRELATIONSHIPDOMAIN_REFERS_TO_PRODUCTVOD" 
KEY ("SUB_OBJECT_PRODUCT_ID") 
SOURCE KEY ("SUB_OBJECT_PRODUCT_ID") REFERENCES "OBJECTRELATIONSHIPDOMAIN" ("SUB_OBJECT_PRODUCT_ID") 
DESTINATION  KEY ("SUB_OBJECT_PRODUCT_ID") REFERENCES "PRODUCTVOD" ("OBJECT_NUMBER") 
NO PROPERTIES,
"OBJECTRELATIONSHIP" AS "OBJECTRELATIONSHIP_HAS_TRANSLATION_OBJECTRELATIONSHIPTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "OBJECTRELATIONSHIP" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTRELATIONSHIPTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_UIPROPERTY_OBJECTUIPROPERTY" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTUIPROPERTY" ("VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_UIPROPERTY_OBJECTUIPROPERTY" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTUIPROPERTY" ("VOD_ID") 
NO PROPERTIES,
"OBJECTUIPROPERTY" AS "OBJECTUIPROPERTY_HAS_TRANSLATION_OBJECTUIPROPERTYTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "OBJECTUIPROPERTY" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTUIPROPERTYTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_LINKEDITEM_LINKEDITEM" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "LINKEDITEM" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_LINKEDITEM_LINKEDITEM" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "LINKEDITEM" ("VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_RESOURCE_RESOURCES" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "RESOURCES" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_RESOURCE_RESOURCES" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "RESOURCES" ("VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_SCRIPT_SCRIPT" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "SCRIPT" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_SCRIPT_SCRIPT" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "SCRIPT" ("VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_ATTRIBUTE_OBJECTATTRIBUTE" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTATTRIBUTE" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_ATTRIBUTE_OBJECTATTRIBUTE" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTATTRIBUTE" ("VOD_ID") 
NO PROPERTIES,
"OBJECTATTRIBUTE" AS "OBJECTATTRIBUTE_HAS_TRANSLATION_OBJECTATTRIBUTETRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "OBJECTATTRIBUTE" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTATTRIBUTETRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"OBJECTATTRIBUTE" AS "OBJECTATTRIBUTE_REFERS_TO_ATTRIBUTEVOD" 
KEY ("ATTRIBUTE_DEFINITION_ID") 
SOURCE KEY ("ATTRIBUTE_DEFINITION_ID") REFERENCES "OBJECTATTRIBUTE" ("ATTRIBUTE_DEFINITION_ID") 
DESTINATION  KEY ("ATTRIBUTE_DEFINITION_ID") REFERENCES "ATTRIBUTEVOD" ("OBJECT_NUMBER") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_RULE_CONSTRAINTRULE" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "CONSTRAINTRULE" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_RULE_CONSTRAINTRULE" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "CONSTRAINTRULE" ("VOD_ID") 
NO PROPERTIES,
"CONSTRAINTRULE" AS "CONSTRAINTRULE_HAS_TRANSLATION_CONSTRAINTRULETRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CONSTRAINTRULE" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "CONSTRAINTRULETRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"OBJECTDEFINITION" AS "OBJECTDEFINITION_HAS_PARENT_OBJECTDEFINITION" 
KEY ("PARENT_VOD_ID") 
SOURCE KEY ("PARENT_VOD_ID") REFERENCES "OBJECTDEFINITION" ("PARENT_VOD_ID") 
DESTINATION  KEY ("PARENT_VOD_ID") REFERENCES "OBJECTDEFINITION" ("VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_PARENT_OBJECTDEFINITION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "OBJECTDEFINITION" ("PARENT_VOD_ID") 
NO PROPERTIES,
"PRODUCTVOD" AS "PRODUCTVOD_HAS_UIOPTION_UIOPTION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "UIOPTION" ("VOD_ID") 
NO PROPERTIES,
"CLASSVOD" AS "CLASSVOD_HAS_UIOPTION_UIOPTION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "UIOPTION" ("VOD_ID") 
NO PROPERTIES,
"UIOPTION" AS "UIOPTION_HAS_GROUP_UIGROUP" 
KEY ("ORIGINAL_ID") 
SOURCE KEY ("ORIGINAL_ID") REFERENCES "UIOPTION" ("ORIGINAL_ID") 
DESTINATION  KEY ("ORIGINAL_ID") REFERENCES "UIGROUP" ("USER_INTERFACE_OPTION_ID") 
NO PROPERTIES,
"UIOPTION" AS "UIOPTION_HAS_RESP_UIRESPONSIBILITY" 
KEY ("ORIGINAL_ID") 
SOURCE KEY ("ORIGINAL_ID") REFERENCES "UIOPTION" ("ORIGINAL_ID") 
DESTINATION  KEY ("ORIGINAL_ID") REFERENCES "UIRESPONSIBILITY" ("USER_INTERFACE_ID") 
NO PROPERTIES,
"UIGROUP" AS "UIGROUP_HAS_TRANSLATION_UIGROUPTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "UIGROUP" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "UIGROUPTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"UIGROUP" AS "UIGROUP_HAS_GROUPITEM_UIGROUPITEM" 
KEY ("ORIGINAL_ID") 
SOURCE KEY ("ORIGINAL_ID") REFERENCES "UIGROUP" ("ORIGINAL_ID") 
DESTINATION  KEY ("ORIGINAL_ID") REFERENCES "UIGROUPITEM" ("USER_INTERFACE_GROUP_ID") 
NO PROPERTIES,
"PROMOTIONDEFINITION" AS "PROMOTIONDEFINITION_HAS_MESSAGES_PROMOTIONMESSAGES" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONMESSAGES" ("PARENT_ROW_ID") 
NO PROPERTIES,
"JOINTWORKSPACE" AS "JOINTWORKSPACE_HAS_TRANSLATION_JOINTWORKSPACETRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "JOINTWORKSPACE" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "JOINTWORKSPACETRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"JOINTWORKSPACE" AS "JOINTWORKSPACE_HAS_ITEMS_JOINTWORKSPACEITEM" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "JOINTWORKSPACE" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "JOINTWORKSPACEITEM" ("JOINT_WORKSPACE_ID") 
NO PROPERTIES,
"JOINTWORKSPACEITEM" AS "JOINTWORKSPACEITEM_HAS_ATTRIBUTE_ATTRIBUTEVOD" 
KEY ("VOD_ID") 
SOURCE KEY ("VOD_ID") REFERENCES "JOINTWORKSPACEITEM" ("VOD_ID") 
DESTINATION  KEY ("VOD_ID") REFERENCES "ATTRIBUTEVOD" ("ROW_ID") 
NO PROPERTIES,
"JOINTWORKSPACEITEM" AS "JOINTWORKSPACEITEM_HAS_CLASS_CLASSVOD" 
KEY ("VOD_ID") 
SOURCE KEY ("VOD_ID") REFERENCES "JOINTWORKSPACEITEM" ("VOD_ID") 
DESTINATION  KEY ("VOD_ID") REFERENCES "CLASSVOD" ("ROW_ID") 
NO PROPERTIES,
"JOINTWORKSPACEITEM" AS "JOINTWORKSPACEITEM_HAS_PRODUCT_PRODUCTVOD" 
KEY ("VOD_ID") 
SOURCE KEY ("VOD_ID") REFERENCES "JOINTWORKSPACEITEM" ("VOD_ID") 
DESTINATION  KEY ("VOD_ID") REFERENCES "PRODUCTVOD" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONDEFINITION" AS "PROMOTIONDEFINITION_HAS_ITEMS_PROMOTIONITEM" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONITEM" ("PROMOTION_ID") 
NO PROPERTIES,
"PROMOTIONITEM" AS "PROMOTIONITEM_REFERS_TO_PRODUCTDEFINITION" 
KEY ("PRODUCT_ID") 
SOURCE KEY ("PRODUCT_ID") REFERENCES "PROMOTIONITEM" ("PRODUCT_ID") 
DESTINATION  KEY ("PRODUCT_ID") REFERENCES "PRODUCTDEFINITION" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONITEM" AS "PROMOTIONITEM_POINTS_TO_PRODUCTVOD" 
KEY ("PRODUCT_ID") 
SOURCE KEY ("PRODUCT_ID") REFERENCES "PROMOTIONITEM" ("PRODUCT_ID") 
DESTINATION  KEY ("PRODUCT_ID") REFERENCES "PRODUCTVOD" ("OBJECT_NUMBER") 
NO PROPERTIES,
"PROMOTIONITEM" AS "PROMOTIONITEM_HAS_ROOT_PROMOTIONITEM" 
KEY ("ROOT_PROMOTION_ITEM_ID") 
SOURCE KEY ("ROOT_PROMOTION_ITEM_ID") REFERENCES "PROMOTIONITEM" ("ROOT_PROMOTION_ITEM_ID") 
DESTINATION  KEY ("ROOT_PROMOTION_ITEM_ID") REFERENCES "PROMOTIONITEM" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONITEM" AS "PROMOTIONITEM_HAS_PARENT_PROMOTIONITEM" 
KEY ("PARENT_PROMOTION_ITEM_ID") 
SOURCE KEY ("PARENT_PROMOTION_ITEM_ID") REFERENCES "PROMOTIONITEM" ("PARENT_PROMOTION_ITEM_ID") 
DESTINATION  KEY ("PARENT_PROMOTION_ITEM_ID") REFERENCES "PROMOTIONITEM" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONITEM" AS "PROMOTIONITEM_HAS_TRANSLATION_PROMOTIONITEMTRANSLATION" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONITEM" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONITEMTRANSLATION" ("PARENT_ROW_ID") 
NO PROPERTIES,
"PROMOTIONITEM" AS "PROMOTIONITEM_HAS_ATTRIBUTE_PROMOTIONITEMXA" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONITEM" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONITEMXA" ("PROMOTION_ITEM_ID") 
NO PROPERTIES,
"PROMOTIONITEMXA" AS "PROMOTIONITEMXA_HAS_ATTRIBUTE_VAL_PROMOTIONITEMVAL" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONITEMXA" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONITEMVAL" ("PARENT_ROW_ID") 
NO PROPERTIES,
"PROMOTIONDEFINITION" AS "PROMOTIONDEFINITION_HAS_CHARGE_PROMOTIONCHARGE" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONCHARGE" ("PROMOTION_ID") 
NO PROPERTIES,
"PROMOTIONDEFINITION" AS "PROMOTIONDEFINITION_HAS_PRICING_PROMOTIONPRICING" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONPRICING" ("PROMOTION_ID") 
NO PROPERTIES,
"PROMOTIONPRICING" AS "PROMOTIONPRICING_REFERS_TO_PRODUCTDEFINITION" 
KEY ("PRODUCT_ID") 
SOURCE KEY ("PRODUCT_ID") REFERENCES "PROMOTIONPRICING" ("PRODUCT_ID") 
DESTINATION  KEY ("PRODUCT_ID") REFERENCES "PRODUCTDEFINITION" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONDEFINITION" AS "PROMOTIONDEFINITION_HAS_MERGE_SPLIT_PROMOTIONMERGESPLIT" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONMERGESPLIT" ("PROMOTION_PRODUCT_ID") 
NO PROPERTIES,
"PROMOTIONMERGESPLIT" AS "PROMOTIONMERGESPLIT_HAS_MERGE_SPLIT_COMP_PROMOTIONMERGESPLITCOMP" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONMERGESPLIT" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONMERGESPLITCOMP" ("PROMOTION_OPERATION_ID") 
NO PROPERTIES,
"PROMOTIONMERGESPLITCOMP" AS "PROMOTIONMERGESPLITCOMP_REFERS_TO_PRODUCTDEFINITION" 
KEY ("PRODUCT_ID") 
SOURCE KEY ("PRODUCT_ID") REFERENCES "PROMOTIONMERGESPLITCOMP" ("PRODUCT_ID") 
DESTINATION  KEY ("PRODUCT_ID") REFERENCES "PRODUCTDEFINITION" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONUPGRADE" AS "SOURCEPROMOTION_REFERS_TO_PROMOTIONDEFINITION" 
KEY ("PRODUCT_ID") 
SOURCE KEY ("PRODUCT_ID") REFERENCES "PROMOTIONUPGRADE" ("PRODUCT_ID") 
DESTINATION  KEY ("PRODUCT_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONUPGRADE" AS "TARGETPROMOTION_REFERS_TO_PROMOTIONDEFINITION" 
KEY ("PARENT_PRODUCT_ID") 
SOURCE KEY ("PARENT_PRODUCT_ID") REFERENCES "PROMOTIONUPGRADE" ("PARENT_PRODUCT_ID") 
DESTINATION  KEY ("PARENT_PRODUCT_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONCONFIGITEM" AS "PROMOTIONCONFIGITEM_REFERS_TO_PRODUCTDEFINITION" 
KEY ("PROD_ID") 
SOURCE KEY ("PROD_ID") REFERENCES "PROMOTIONCONFIGITEM" ("PROD_ID") 
DESTINATION  KEY ("PROD_ID") REFERENCES "PRODUCTDEFINITION" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONDEFINITION" AS "PROMOTIONDEFINITION_HAS_TERMS_PROMOTIONTERM" 
KEY ("ROW_ID") 
SOURCE KEY ("ROW_ID") REFERENCES "PROMOTIONDEFINITION" ("ROW_ID") 
DESTINATION  KEY ("ROW_ID") REFERENCES "PROMOTIONTERM" ("PRODUCT_ID") 
NO PROPERTIES,
"PROMOTIONTERM" AS "PROMOTIONTERM_REFERS_TO_PRODUCTDEFINITION" 
KEY ("ASSOCIATE_PRODUCT_ID") 
SOURCE KEY ("ASSOCIATE_PRODUCT_ID") REFERENCES "PROMOTIONTERM" ("ASSOCIATE_PRODUCT_ID") 
DESTINATION  KEY ("ASSOCIATE_PRODUCT_ID") REFERENCES "PRODUCTDEFINITION" ("ROW_ID") 
NO PROPERTIES,
"PROMOTIONITEM" AS "PROMOTIONITEM_DOMAIN_PRODUCTVOD" 
KEY ("SUB_OBJECT_VOD_NUMBER") 
SOURCE KEY ("SUB_OBJECT_VOD_NUMBER") REFERENCES "PROMOTIONITEM" ("SUB_OBJECT_VOD_NUMBER") 
DESTINATION  KEY ("SUB_OBJECT_VOD_NUMBER") REFERENCES "PRODUCTVOD" ("OBJECT_NUMBER") 
NO PROPERTIES
)
